In [2]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
DATA_PATH = "data/pubmedqa_clean.csv"

df = pd.read_csv(DATA_PATH)
df = df.dropna(subset=["medical_text"])

print(df, df.shape)
df.head()

     question_id  ...                                       medical_text
0       21645374  ...  Question: Do mitochondria play a role in remod...
1       16418930  ...  Question: Landolt C and snellen e acuity: diff...
2        9488747  ...  Question: Syncope during bathing in infants, a...
3       17208539  ...  Question: Are the long-term results of the tra...
4       10808977  ...  Question: Can tailored interventions increase ...
..           ...  ...                                                ...
995      8921484  ...  Question: Does gestational age misclassificati...
996     16564683  ...  Question: Is there any interest to perform ult...
997     23147106  ...  Question: Is peak concentration needed in ther...
998     21550158  ...  Question: Can autologous platelet-rich plasma ...
999     17559449  ...  Question: Are sugars-free medicines more erosi...

[1000 rows x 11 columns] (1000, 11)

   question_id  ...                                       medical_text
0     21645374  ...  Question: Do mitochondria play a role in remod...
1     16418930  ...  Question: Landolt C and snellen e acuity: diff...
2      9488747  ...  Question: Syncope during bathing in infants, a...
3     17208539  ...  Question: Are the long-term results of the tra...
4     10808977  ...  Question: Can tailored interventions increase ...

[5 rows x 11 columns]

In [7]:
vectorizer = TfidfVectorizer(
    stop_words = "english",
    max_features = 10000
)

medical_vectors = vectorizer.fit_transform(df["medical_text"])
print(medical_vectors.shape)

(1000, 10000)

In [13]:
def medical_records(query, top_n = 5):
    if not query.strip():
        return "Please enter a valid query."
    
    query_vector = vectorizer.transform([query])
    similarity_scores = cosine_similarity(query_vector, medical_vectors).flatten()
    top_indices = similarity_scores.argsort()[::-1][:top_n]
    
    results = df.iloc[top_indices].copy()
    results["similarity_score"] = similarity_scores[top_indices]
    
    return results[
        [
            "question",
            "context_text",
            "long_answer",
            "final_decision",
            "similarity_score" 
        ]
    ]

In [14]:
medical_records("Does aspirin reduce cardiovascular risk?", top_n = 5)

                                              question  ... similarity_score
686  Can common carotid intima media thickness serv...  ...         0.201875
929  Do "America's Best Hospitals" perform better f...  ...         0.152177
392  Is high-sensitivity C-reactive protein associa...  ...         0.132539
19   Cardiovascular risk in a rural adult West Afri...  ...         0.128881
297  Is cardiovascular evaluation necessary prior t...  ...         0.114844

[5 rows x 5 columns]

In [15]:
medical_records("What are the side effects of statins?", top_n = 5)

                                              question  ... similarity_score
52   Does pretreatment with statins improve clinica...  ...         0.642612
339  Do preoperative statins reduce atrial fibrilla...  ...         0.207196
114  Are physicians aware of the side effects of an...  ...         0.086183
571  Adults with mild intellectual disabilities: ca...  ...         0.078033
982  Intravenous administration of metoclopramide b...  ...         0.068454

[5 rows x 5 columns]